### ISSUE TITLE
Start monitoring automatically?

### ISSUE THREAD

**Issue by niccokunzmann** [niccokunzmann/hanging_threads#13]
The only purpose of this module is to monitor and print.
We could start monitoring automatically

- for convenience/historical reasons
- because everybody will start monitoring nonetheless. We just remove one line.

@artemrizhov What do you think?
We could start monitoring and then allow parameters to be changed while it runs.
(And we can stop monitoring if it is a use-case)

**Comment by artemrizhov** [comment]
Hi! Thanks for asking. I was thinking about this too, and finished with the following conclusion.

**Upsides:**
U1. We can start monitoring with just one import. This may be especially useful if you need to do this quickly when debugging the app. Looks like a resonable idea.
U2. Backward compatibility, if it's important.
(Is there anything else?)

**Downsides:**
D1. It probably does not conform the [Zen of Python](https://www.python.org/dev/peps/pep-0020/). This solution seems implicit. The Zen of Python says "Explicit is better than implicit". What it does is implicit start of monitoring. This may lead into misunderstanding when a developer will not see the real action under import. It also seems that import is used for things that it is not intended for - to start some work. Same document says "There should be one-- and preferably only one --obvious way to do it." From this point of view the it is probably not good idea to use the import statement to run some worker while is designed to "[gain access to the code in another mod](https://www.python.org/dev/peps/pep-0020/)". The one obvious way to start doing something is applying a callable object.
D2. Right now I'm working on a feature that will allow to avoid dumps of main loops in multithreading apps such as Django sites. This feature should be enabled before the monitoring thread is started.
D3. It may be impossible to override some aspects of behaviour without modifying the source code if the monitor is already started.

Actually I think D1 is cause of problems such as D2 and D3, this demostrates why D1 is important

We also can see examples in another projects. For example in Django if we need to start a WSGI handler we do this as following
```
from django.core.handlers.wsgi import WSGIHandler
application = WSGIHandler()
```
Actual handling of WSGI requests is started via call to WSGIHandler constructor, not via import. This is a common technique that we can see here and there.

What about easy way to start the monitor with a simple one-liner, well, I'm in doubt. I can't imagine how to start the thread without import, and how to start automatically without violation PEP20. As a compromise it is possible to add submodule `autostart` so that you can do the following:
```
from hanging_threads import autostart
```
But this also is not as easy as `import hanging_threads` because you have to remember two names instead of just one module name. And this is definitely should not be used in production, but only for quick debugging. It is probably ok for debugging purposes because debugging almost always uses quick and dirty solutions.

**Comment by niccokunzmann** [comment]
Okay, I agree, let us make it explicit.

**Comment by niccokunzmann** [comment]
Can we close this? Is there anything else to be done?

**Comment by artemrizhov** [comment]
I think this can be closed.
